apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: YOUR-UCD-APP
  name: ucd-apps-builds
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "your-ucd-app-image-name:latest"
  resources: {}
  source:
    # git:
    #   ref: master
    #   uri: https://github.com/weepee-org/openshift-example-project.git
    # contextDir: hhvm/
    # type: Git
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
